---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: {{.HwOffloadNodeLabel}}
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,{{.HwOffloadNodeLabel}}]}
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/{{.HwOffloadNodeLabel}}: ""
