name: ovs-vswitchd.service
dropins:
- name: 10-hw-offload.conf
  contents: |
    [Service]
    ExecStartPre=/bin/ovs-vsctl set Open_vSwitch . other_config:hw-offload=true
    ExecStartPre=/bin/ovs-vsctl set Open_vSwitch . other_config:tc-policy=skip_sw
